// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Actions
{
    public int Id { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// Tác nghiệp trước
    /// </summary>
    public string Actions1 { get; set; }

    /// <summary>
    /// Tác nghiệp trước
    /// </summary>
    public string StatusActions { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string Roles { get; set; }

    public virtual ICollection<OrderActions> OrderActions { get; set; } = new List<OrderActions>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();
}