// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class AlePayTransactionInfos
{
    public int Id { get; set; }

    public string TransactionCode { get; set; }

    public string OrderCode { get; set; }

    public string Amount { get; set; }

    public string Currency { get; set; }

    public string BuyerEmail { get; set; }

    public string BuyerPhone { get; set; }

    public string CardNumber { get; set; }

    public string BuyerName { get; set; }

    public string Status { get; set; }

    public string Message { get; set; }

    public bool? Installment { get; set; }

    public bool? Is3D { get; set; }

    public int? Month { get; set; }

    public string BankCode { get; set; }

    public string BankName { get; set; }

    public string Method { get; set; }

    public string TransactionTime { get; set; }

    public string SuccessTime { get; set; }

    public double? MerchantFee { get; set; }

    public double? PayerFee { get; set; }

    public string BankHotline { get; set; }

    public string SubMtid { get; set; }

    public string NameMtid { get; set; }

    public string Reason { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public int? PaymentChannel { get; set; }

    public string IpCallIpn { get; set; }
}