// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class AppController
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string Route { get; set; }

    public int? Index { get; set; }

    public int? ServiceId { get; set; }

    public string GroupName { get; set; }

    public virtual Permissions IdNavigation { get; set; }
}