// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Banks
{
    public int Id { get; set; }

    /// <summary>
    /// Mã
    /// </summary>
    public string Code { get; set; }

    /// <summary>
    /// Tên ngân hàng
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Hỗ trợ rút tiền qua thẻ ATM
    /// </summary>
    public bool? IsSupportAtm { get; set; }

    /// <summary>
    /// Hỗ trợ rút tiền qua số tài khoản
    /// </summary>
    public bool? IsSupportBank { get; set; }

    public bool? IsSupportPayment { get; set; }

    public int? BankType { get; set; }

    public string LogoLink { get; set; }

    public int? DisplayOrder { get; set; }

    public double? MinAmount { get; set; }

    public double? MaxAmount { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ICollection<Points> Points { get; set; } = new List<Points>();

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}