// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Banners
{
    public int Id { get; set; }

    public int IdCategory { get; set; }

    public string Type { get; set; }

    /// <summary>
    /// Id tham chiếu
    /// </summary>
    public int? ObjectId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    /// <summary>
    /// Link
    /// </summary>
    public string Url { get; set; }

    public int? Sort { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string ImageWeb { get; set; }

    public bool? IsShowHome { get; set; }

    /// <summary>
    /// Hiển thị theo loại khách hàng
    /// </summary>
    public string ShowUserType { get; set; }

    public virtual BannerCategories IdCategoryNavigation { get; set; }
}