// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Brands
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// Logo
    /// </summary>
    public string Image { get; set; }

    /// <summary>
    /// Xuất xứ
    /// </summary>
    public int? IdCountry { get; set; }

    /// <summary>
    /// Thứ tự
    /// </summary>
    public int? Sort { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool? IsShowHome { get; set; }

    public string Video { get; set; }

    public string ListImages { get; set; }

    public string ImageBanner { get; set; }

    public double? SumRate { get; set; }

    public int? CountRate { get; set; }

    public int? CountComment { get; set; }

    public string ImageAbouts { get; set; }

    public virtual Countries IdCountryNavigation { get; set; }

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();
}