// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class CallTransactions
{
    public int Id { get; set; }

    public string TransactionId { get; set; }

    public string TenantId { get; set; }

    public string Direction { get; set; }

    public string SourceNumber { get; set; }

    public string DestinationNumber { get; set; }

    public string Disposition { get; set; }

    public string BillSec { get; set; }

    public string RecordSeconds { get; set; }

    public string TimeStartToAnswer { get; set; }

    public string RecordingFile { get; set; }

    public string RecordingData { get; set; }

    public int? SipUser { get; set; }

    public string CreatedDateOmi { get; set; }

    public string LastUpdatedDateOmi { get; set; }

    public bool? IsAutoCall { get; set; }

    public string Ivr { get; set; }

    public string Provider { get; set; }

    public int? Duration { get; set; }

    public string State { get; set; }

    public string CallUuid { get; set; }

    public string FromNumber { get; set; }

    public string ToNumber { get; set; }

    public string Hotline { get; set; }

    public bool? IsHaveForwardOut { get; set; }

    public string BillSecForwardOut { get; set; }

    public double? CallOutPrice { get; set; }

    public string Note { get; set; }

    public string Tag { get; set; }

    public string InviteFailureStatus { get; set; }

    public int? AnswerSec { get; set; }

    public string AutocallUuid { get; set; }

    public string SipNumber { get; set; }

    public string PhoneNumber { get; set; }

    public string TransferHistories { get; set; }

    public string UserDataStr { get; set; }

    public string EndbyName { get; set; }

    public bool? IsVoicemail { get; set; }

    public string RecordingFileVoicemail { get; set; }

    public string User { get; set; }

    public string CustomerFullName { get; set; }

    public string CustomerFullNameUnsigned { get; set; }

    public string CreateById { get; set; }

    public string CreateByName { get; set; }

    public string CreateByContactId { get; set; }

    public string CreateByAvatar { get; set; }

    public string CreateByGender { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }
}