// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Chats
{
    public int Id { get; set; }

    /// <summary>
    /// Cuộc trò truyện
    /// </summary>
    public int ChatTopicId { get; set; }

    /// <summary>
    /// Khách hàng
    /// </summary>
    public int CustomerId { get; set; }

    public int? IdOrder { get; set; }

    /// <summary>
    /// Nội dung phản hồi
    /// </summary>
    public string Message { get; set; }

    /// <summary>
    /// Ảnh
    /// </summary>
    public string Images { get; set; }

    /// <summary>
    /// Trạng thái
    /// </summary>
    public int? IdStatus { get; set; }

    public bool? IsReaded { get; set; }

    public bool? IsDeleted { get; set; }

    public int? UserId { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ChatTopics ChatTopic { get; set; }
}