// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Clients
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string Code { get; set; }

    public string Avatar { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string FacebookId { get; set; }

    public string Email { get; set; }

    public int? IdProvince { get; set; }

    public int? IdDistrict { get; set; }

    public int? IdWard { get; set; }

    public string Address { get; set; }

    public int? OrderNumber { get; set; }

    public bool? IsConnectLogistics { get; set; }

    /// <summary>
    /// Đơn vị giao hàng mặc định
    /// </summary>
    public int? IdDeliveryUnit { get; set; }

    public string IdTranport { get; set; }

    public bool? IsSendSms { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string LogisticsUsername { get; set; }

    public int? LogisticsPickWorkShift { get; set; }

    public int? LogisticsPickOption { get; set; }

    public int? LogisticsId { get; set; }

    public string LogisticsServices { get; set; }

    /// <summary>
    /// Có tác nghiệp ship tự động trên hệ thống hay ko
    /// </summary>
    public bool? IsAutoShip { get; set; }

    /// <summary>
    /// Mô tả, thông tin doanh nghiệp
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Phí doanh nghiệp phải trả cho sàn
    /// </summary>
    public double? FeeBussiness { get; set; }

    /// <summary>
    /// Mô tả, thông tin cho Ship biết ở đơn hàng giao vận
    /// </summary>
    public string DescriptionShip { get; set; }

    /// <summary>
    /// Mô tả, hiển thị ở giỏ hàng
    /// </summary>
    public string DescriptionCart { get; set; }

    /// <summary>
    /// Khoảng cách giao hàng từ cửa hàng ( Nếu Thiết lập IsAutoShip = 1)
    /// </summary>
    public double? ShipDistance { get; set; }

    /// <summary>
    /// Khoảng cách vị trí ước tính ( Nếu Thiết lập IsAutoShip = 1)
    /// </summary>
    public double? ShipLocation { get; set; }

    /// <summary>
    /// Kiểm tra hàng tồn kho trong cửa hàng
    /// </summary>
    public bool? IsCheckInventory { get; set; }

    public string ImageBanner { get; set; }

    public double? SumRate { get; set; }

    public int? CountRate { get; set; }

    public int? CountComment { get; set; }

    public string ImageAbouts { get; set; }

    /// <summary>
    /// Cho phép đặt hàng sau x ngày
    /// </summary>
    public int? ExtendDateOrder { get; set; }

    public virtual ICollection<DeliveryServices> DeliveryServices { get; set; } = new List<DeliveryServices>();

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();

    public virtual ICollection<Shops> Shops { get; set; } = new List<Shops>();

    public virtual ICollection<Suppliers> Suppliers { get; set; } = new List<Suppliers>();

    public virtual ICollection<WarehouseInOuts> WarehouseInOuts { get; set; } = new List<WarehouseInOuts>();

    public virtual ICollection<Warehouses> Warehouses { get; set; } = new List<Warehouses>();
}