// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Comments
{
    public int Id { get; set; }

    public int? IdParent { get; set; }

    /// <summary>
    /// CTV
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Mã sản phẩm
    /// </summary>
    public int IdFeed { get; set; }

    public string Content { get; set; }

    public string Attachment { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Feeds IdFeedNavigation { get; set; }

    public virtual Users User { get; set; }

    public virtual ICollection<WmFeedCommentLikes> WmFeedCommentLikes { get; set; } = new List<WmFeedCommentLikes>();
}