// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Companys
{
    public int Id { get; set; }

    public string TaxCode { get; set; }

    public string LegalName { get; set; }

    public string AdressLine { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string FaxNumber { get; set; }

    public string BankName { get; set; }

    public string Website { get; set; }

    public string BankAccount { get; set; }

    public string UserNameInvoice { get; set; }

    public string PasswordInvoice { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<InvoiceTemplates> InvoiceTemplates { get; set; } = new List<InvoiceTemplates>();
}