// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Contents
{
    public int Id { get; set; }

    public int IdProduct { get; set; }

    /// <summary>
    /// Mô tả
    /// </summary>
    public string Images { get; set; }

    public string Content { get; set; }

    public int? OrderNumber { get; set; }

    /// <summary>
    /// 1: doanh nghiệp tạo. 2: cá nhân tạo
    /// </summary>
    public int? Type { get; set; }

    /// <summary>
    /// 1. private, 2. Chờ duyệt, 3: đã duyệt, 4: không được duyệt
    /// </summary>
    public int? Status { get; set; }

    /// <summary>
    /// Comment khi không được duyệt
    /// </summary>
    public string Comment { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Products IdProductNavigation { get; set; }
}