// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class CourseLessions
{
    public int Id { get; set; }

    public int IdCourse { get; set; }

    public int IdLession { get; set; }

    public virtual Courses IdCourseNavigation { get; set; }

    public virtual Lessons IdLessionNavigation { get; set; }
}