// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Customers
{
    /// <summary>
    /// 1: CTV, 2: DN,
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 1: CTV, 2: DN,
    /// </summary>
    public int? UserId { get; set; }

    /// <summary>
    /// Id cha
    /// </summary>
    public int? IdParent { get; set; }

    public string Code { get; set; }

    public int? IdClient { get; set; }

    public int? IdLevel { get; set; }

    /// <summary>
    /// 1.CTV, 2. DN, 3 Shop
    /// </summary>
    public int? IdType { get; set; }

    public string Avatar { get; set; }

    public string UserName { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Cmt { get; set; }

    public string CmtFront { get; set; }

    public string CmtBackside { get; set; }

    /// <summary>
    /// Duyệt cmt
    /// </summary>
    public bool? IsApproveCmt { get; set; }

    /// <summary>
    /// Tên miền
    /// </summary>
    public string Protocol { get; set; }

    /// <summary>
    /// Tên miền
    /// </summary>
    public string Domain { get; set; }

    /// <summary>
    /// 2: Đã thành công, 1: đang xử lý
    /// </summary>
    public int? DomainStatus { get; set; }

    public string FacebookId { get; set; }

    public string FacebookName { get; set; }

    public string Email { get; set; }

    public double? Balance { get; set; }

    /// <summary>
    /// Tiền đang luôn chuyển
    /// </summary>
    public double? CashInTransit { get; set; }

    /// <summary>
    /// Tổng thưởng
    /// </summary>
    public double? TotalReward { get; set; }

    public int? IdAddress { get; set; }

    public int? IdProvince { get; set; }

    public int? IdDistrict { get; set; }

    public int? IdWard { get; set; }

    public string Address { get; set; }

    public int? IdBank { get; set; }

    /// <summary>
    /// Chi nhánh
    /// </summary>
    public string BankBranch { get; set; }

    /// <summary>
    /// Họ và tên
    /// </summary>
    public string BankFullName { get; set; }

    /// <summary>
    /// Số tài khoản
    /// </summary>
    public string BankNumber { get; set; }

    /// <summary>
    /// Số tài khoản
    /// </summary>
    public string BankCardNumber { get; set; }

    public bool? IsTrial { get; set; }

    /// <summary>
    /// Bắt logout đăng nhập lại
    /// </summary>
    public bool? IsLogout { get; set; }

    /// <summary>
    /// Bắt logout đăng nhập lại
    /// </summary>
    public bool? IsLocked { get; set; }

    /// <summary>
    /// Duyệt tài khoản
    /// </summary>
    public bool? IsApproved { get; set; }

    /// <summary>
    /// Người hỗ trợ
    /// </summary>
    public int? IdSupport { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    /// <summary>
    /// Người giới thiệu
    /// </summary>
    public int? ReferralUserId { get; set; }

    /// <summary>
    /// Mã giới thiệu
    /// </summary>
    public string ReferralCode { get; set; }

    /// <summary>
    /// Là tài khoản doanh nghiệp
    /// </summary>
    public bool? IsAdminClient { get; set; }

    public int? IdShop { get; set; }

    public bool? RequestCancel { get; set; }

    public DateTime? RequestCancelDate { get; set; }

    public bool? Gender { get; set; }

    public DateOnly? Birthday { get; set; }

    public bool? IsOmiCall { get; set; }

    public string OmiCallRole { get; set; }

    public string OmiCallPassword { get; set; }

    public int? OmiCallSipUser { get; set; }

    public string OmiCallSecretKey { get; set; }

    public string OmiCallDomain { get; set; }

    public bool? IsKol { get; set; }

    public int? CountOrdersFinish { get; set; }

    public double? TotalOrdersFinish { get; set; }

    public virtual Users User { get; set; }
}