// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class DeliveryShops
{
    public int Id { get; set; }

    public int? IdDeliveryServices { get; set; }

    public int? IdShops { get; set; }

    public virtual DeliveryServices IdDeliveryServicesNavigation { get; set; }

    public virtual Shops IdShopsNavigation { get; set; }
}