// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class DeliveryServices
{
    public int Id { get; set; }

    /// <summary>
    /// Id doanh nghiệp
    /// </summary>
    public int? IdClient { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// Token sử dụng dịch vụ vận chuyển
    /// </summary>
    public string Token { get; set; }

    /// <summary>
    /// nhà cung cấp dịch vụ vẫn chuyển
    /// </summary>
    public int? IdDeliveryCategory { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ICollection<DeliveryShops> DeliveryShops { get; set; } = new List<DeliveryShops>();

    public virtual Clients IdClientNavigation { get; set; }
}