// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

/// <summary>
/// Nhãn đơn hàng
/// </summary>
public partial class DeliveryTags
{
    public int Id { get; set; }

    public int? IdDeliveryCategory { get; set; }

    public int? Code { get; set; }

    public string Description { get; set; }

    public string Detail { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }
}