// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Districts
{
    public int Id { get; set; }

    public int IdProvince { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Provinces IdProvinceNavigation { get; set; }

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public virtual ICollection<SaleOrders> SaleOrders { get; set; } = new List<SaleOrders>();

    public virtual ICollection<Wards> Wards { get; set; } = new List<Wards>();
}