// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Faqs
{
    public int Id { get; set; }

    /// <summary>
    /// 1. Hướng dẫn bán hàng, 2. Hướng dẫn sử dụng
    /// </summary>
    public int Type { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Detail { get; set; }

    /// <summary>
    /// Video
    /// </summary>
    public string UrlVideo { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    public int? Sort { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }
}