// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Feedbacks
{
    public int Id { get; set; }

    public int? IdOrder { get; set; }

    public int? IdFeedbackCategorie { get; set; }

    /// <summary>
    /// Nội dung phản hồi
    /// </summary>
    public string Content { get; set; }

    /// <summary>
    /// Ảnh
    /// </summary>
    public string Images { get; set; }

    /// <summary>
    /// Trạng thái trả lời
    /// </summary>
    public int? IdFeedbackStatus { get; set; }

    /// <summary>
    /// Trạng thái đơn hàng hiện tại
    /// </summary>
    public int? IdStatus { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string Note { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual FeedbackCategories IdFeedbackCategorieNavigation { get; set; }

    public virtual FeedbackStatus IdFeedbackStatusNavigation { get; set; }

    public virtual Orders IdOrderNavigation { get; set; }
}