// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class FeedbackCategories
{
    public int Id { get; set; }

    /// <summary>
    /// Nội dung phản hồi
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Trạng thái đơn hàng hiện tại
    /// </summary>
    public int? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ICollection<Feedbacks> Feedbacks { get; set; } = new List<Feedbacks>();
}