// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class FoodLikes
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? IdFood { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual Foods IdFoodNavigation { get; set; }

    public virtual Users User { get; set; }
}