// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Foods
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Detail { get; set; }

    public string Image { get; set; }

    public bool? IsActived { get; set; }

    public int? Sort { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ShowFromDate { get; set; }

    public DateTime? ShowToDate { get; set; }

    public bool? IsShowHome { get; set; }

    public string Banner { get; set; }

    public virtual ICollection<FoodJoinCategories> FoodJoinCategories { get; set; } = new List<FoodJoinCategories>();

    public virtual ICollection<FoodLikes> FoodLikes { get; set; } = new List<FoodLikes>();

    public virtual ICollection<FoodProducts> FoodProducts { get; set; } = new List<FoodProducts>();
}