// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class FoodJoinCategories
{
    public int Id { get; set; }

    public int IdCategory { get; set; }

    public int IdFood { get; set; }

    public virtual FoodCategories IdCategoryNavigation { get; set; }

    public virtual Foods IdFoodNavigation { get; set; }
}