// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Groups
{
    public int Id { get; set; }

    /// <summary>
    /// Mã nhóm
    /// </summary>
    public string Code { get; set; }

    /// <summary>
    /// Trưởng nhóm
    /// </summary>
    public int UserId { get; set; }

    public string Name { get; set; }

    public string Avatar { get; set; }

    /// <summary>
    /// Link nhóm
    /// </summary>
    public string Link { get; set; }

    /// <summary>
    /// Mô tả
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Nhóm kín
    /// </summary>
    public bool? IsPrivate { get; set; }

    /// <summary>
    /// Tự động duyệt
    /// </summary>
    public bool? IsAutoApproved { get; set; }

    public bool? IsActive { get; set; }

    /// <summary>
    /// Được nhận thưởng
    /// </summary>
    public bool? IsActiveReward { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ICollection<GroupRegs> GroupRegs { get; set; } = new List<GroupRegs>();
}