// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class GroupRegs
{
    public int Id { get; set; }

    public int UserId { get; set; }

    /// <summary>
    /// Nhóm
    /// </summary>
    public int IdGroup { get; set; }

    /// <summary>
    /// 0: Chờ duyệt, 1: đã duyệt, 2: CTV hủy, 3 Leader từ chối, 4: Leader mời vào nhóm, 5: CTV từ chối lời mời, 6: Leader xóa lời mời
    /// </summary>
    public int? Status { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Groups IdGroupNavigation { get; set; }

    public virtual Users User { get; set; }
}