// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class HtMenuUser
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? MenuId { get; set; }

    public DateTime? Created { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? Modified { get; set; }

    public bool? IsDeleted { get; set; }

    public int? ModifiedBy { get; set; }

    public virtual HtMenu Menu { get; set; }
}