// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class HtMenu
{
    public int Id { get; set; }

    public int? IdCha { get; set; }

    public string Ma { get; set; }

    public string Ten { get; set; }

    public string Url { get; set; }

    public string Icon { get; set; }

    public int? ThuTu { get; set; }

    public string IdDuongDan { get; set; }

    public string TenDuongDan { get; set; }

    public int? PhanHe { get; set; }

    public string PhanQuyen { get; set; }

    public int? TrangThai { get; set; }

    public DateTime? Created { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? Modified { get; set; }

    public int? ModifiedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<HtMenuUser> HtMenuUser { get; set; } = new List<HtMenuUser>();
}