// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Invoices
{
    public int Id { get; set; }

    public string ErpId { get; set; }

    /// <summary>
    /// Tác nghiệp trước
    /// </summary>
    public string CreatorErp { get; set; }

    /// <summary>
    /// Tác nghiệp trước
    /// </summary>
    public string TransactionId { get; set; }

    public int? InvoiceTemplateId { get; set; }

    public int? TemplateNo { get; set; }

    public string SerialNo { get; set; }

    public string InvoiceNo { get; set; }

    public string Note { get; set; }

    public int? InvoiceStatus { get; set; }

    public int? SignStatus { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? TotalVatAmount { get; set; }

    public double? TotalDiscountAmountBeforeTax { get; set; }

    public double? TotalDiscountPercentAfterTax { get; set; }

    public double? TotalDiscountAmountAfterTax { get; set; }

    public string FromCurrency { get; set; }

    public string Currency { get; set; }

    public int? RoundingCurrency { get; set; }

    public int? CurrencyConversion { get; set; }

    public double? ExchangeRate { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string PaymentAmountWords { get; set; }

    public string PaymentAmountWordsEn { get; set; }

    public decimal? TotalPaymentAmount { get; set; }

    public string BuyerId { get; set; }

    public string BuyerCode { get; set; }

    public string BuyerIdErp { get; set; }

    public string BuyerEmail { get; set; }

    public string BuyerFullName { get; set; }

    public string BuyerLegalName { get; set; }

    public string BuyerTaxCode { get; set; }

    public string BuyerAddressLine { get; set; }

    public string BuyerDistrictName { get; set; }

    public string BuyerCityName { get; set; }

    public string BuyerCountryCode { get; set; }

    public string BuyerPhoneNumber { get; set; }

    public string BuyerFaxNumber { get; set; }

    public string BuyerBankName { get; set; }

    public string BuyerBankAccount { get; set; }

    public string SellerId { get; set; }

    public string SellerLegalName { get; set; }

    public string SellerTaxCode { get; set; }

    public string SellerAddressLine { get; set; }

    public string SellerCountryCode { get; set; }

    public string SellerDistrictName { get; set; }

    public string SellerCityName { get; set; }

    public string SellerPhoneNumber { get; set; }

    public string SellerFaxNumber { get; set; }

    public string SellerEmail { get; set; }

    public string SellerBankName { get; set; }

    public string SellerBankAccount { get; set; }

    public string SellerFullName { get; set; }

    public DateTime? SellerSignedTime { get; set; }

    public string SellerFullNameSigned { get; set; }

    public string SellerSignedId { get; set; }

    public DateTime? PrintedTime { get; set; }

    public string FullNamePrinter { get; set; }

    public string PrintedId { get; set; }

    public string FileDocumentId { get; set; }

    public DateTime? DocumentDate { get; set; }

    public string DocumentNo { get; set; }

    public string DocumentReason { get; set; }

    public string FileNameOfDocument { get; set; }

    public string InvoiceReferenceId { get; set; }

    public string TransactionData { get; set; }

    public string Content { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<InvoiceDetails> InvoiceDetails { get; set; } = new List<InvoiceDetails>();

    public virtual ICollection<InvoiceFiles> InvoiceFiles { get; set; } = new List<InvoiceFiles>();

    public virtual ICollection<InvoiceTaxBreakdowns> InvoiceTaxBreakdowns { get; set; } = new List<InvoiceTaxBreakdowns>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();
}