// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class InvoiceFiles
{
    public int Id { get; set; }

    public int? IdInvoice { get; set; }

    /// <summary>
    /// Tác nghiệp trước
    /// </summary>
    public string DataFile { get; set; }

    public int? FileType { get; set; }

    /// <summary>
    /// Tác nghiệp trước
    /// </summary>
    public string ContentType { get; set; }

    public string ErpId { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Invoices IdInvoiceNavigation { get; set; }
}