// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class LessionProducts
{
    public int Id { get; set; }

    public int IdLession { get; set; }

    public int IdProduct { get; set; }

    public virtual Lessons IdLessionNavigation { get; set; }

    public virtual Products IdProductNavigation { get; set; }
}