// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

/// <summary>
/// Bài giảng
/// </summary>
public partial class Lessons
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Image { get; set; }

    /// <summary>
    /// Tổ chức
    /// </summary>
    public string Institution { get; set; }

    /// <summary>
    /// giảng viên, người hướng dẫn
    /// </summary>
    public string Instructor { get; set; }

    /// <summary>
    /// Những gì bạn sẽ học
    /// </summary>
    public string Achievements { get; set; }

    /// <summary>
    /// Yêu cầu khóa học
    /// </summary>
    public string Prerequisites { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// Đối tượng tham gia khóa học
    /// </summary>
    public string Objects { get; set; }

    /// <summary>
    /// Cấp độ, độ khó khóa học
    /// </summary>
    public string DifficultyLevel { get; set; }

    /// <summary>
    /// Loại chứng nhận khi hoàn thành
    /// </summary>
    public string Certificate { get; set; }

    /// <summary>
    /// Giáo trình học
    /// </summary>
    public string Syllabus { get; set; }

    /// <summary>
    /// Tổng thời gian của khóa học
    /// </summary>
    public double? TotalTimeVideo { get; set; }

    /// <summary>
    /// Tổng số phần học trong khóa học
    /// </summary>
    public int? TotalPart { get; set; }

    /// <summary>
    /// Tổng số bài giảng
    /// </summary>
    public int? TotalLesson { get; set; }

    /// <summary>
    /// Tổng số lượt thích
    /// </summary>
    public int? TotalLike { get; set; }

    /// <summary>
    /// Tổng số lượt bình luận
    /// </summary>
    public int? TotalComment { get; set; }

    /// <summary>
    /// Tổng số sao đánh giá
    /// </summary>
    public double? SumRate { get; set; }

    /// <summary>
    /// Sắp xếp thứ tự
    /// </summary>
    public int? Sort { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string ShowUserType { get; set; }

    public bool? IsShowHome { get; set; }

    public virtual ICollection<CourseLessions> CourseLessions { get; set; } = new List<CourseLessions>();

    public virtual ICollection<LessionLikes> LessionLikes { get; set; } = new List<LessionLikes>();

    public virtual ICollection<LessionPathologies> LessionPathologies { get; set; } = new List<LessionPathologies>();

    public virtual ICollection<LessionProducts> LessionProducts { get; set; } = new List<LessionProducts>();

    public virtual ICollection<LessionRates> LessionRates { get; set; } = new List<LessionRates>();

    public virtual ICollection<LessonDetails> LessonDetails { get; set; } = new List<LessonDetails>();

    public virtual ICollection<PartLessions> PartLessions { get; set; } = new List<PartLessions>();

    public virtual ICollection<QuestionLessions> QuestionLessions { get; set; } = new List<QuestionLessions>();
}