// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class News
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Detail { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    public int? Sort { get; set; }

    public int? IdCategory { get; set; }

    public string TitleSeo { get; set; }

    public string DescriptionSeo { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual NewsCategories IdCategoryNavigation { get; set; }
}