// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Notifications
{
    public int Id { get; set; }

    /// <summary>
    /// Mã
    /// </summary>
    public string Code { get; set; }

    /// <summary>
    /// Tên ngân hàng
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Tên ngân hàng
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// Tên ngân hàng
    /// </summary>
    public string Content { get; set; }

    /// <summary>
    /// Tên ngân hàng
    /// </summary>
    public string Image { get; set; }

    /// <summary>
    /// Tên ngân hàng
    /// </summary>
    public string Link { get; set; }

    public int? Type { get; set; }

    public string SendTo { get; set; }

    public bool? IsSent { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? SentUserId { get; set; }

    public DateTime? SentDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }
}