// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class OmiCallLogs
{
    public int Id { get; set; }

    public DateTime? AnswerTime { get; set; }

    public string Direction { get; set; }

    public string DirectionTxt { get; set; }

    public int? Duration { get; set; }

    public string DurationTxt { get; set; }

    public string EndCause { get; set; }

    public DateTime? EndTime { get; set; }

    public bool? IsAccepted { get; set; }

    public string Phone { get; set; }

    public string RemoteAvatar { get; set; }

    public string RemoteName { get; set; }

    public string RemoteNumber { get; set; }

    public int? Ringing { get; set; }

    public string RingingTxt { get; set; }

    public string SipDomain { get; set; }

    public string SipNumber { get; set; }

    public int? SipUser { get; set; }

    public string SneakyType { get; set; }

    public DateTime? StartTime { get; set; }

    public string StartTimeTxt { get; set; }

    public string Status { get; set; }

    public string StatusTxt { get; set; }

    public int? TotalDuration { get; set; }

    public string Uuid { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? IdOrder { get; set; }

    public int? IdAction { get; set; }

    public int? UserId { get; set; }

    public string Note { get; set; }
}