// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Orders
{
    public int Id { get; set; }

    public int? IdParent { get; set; }

    /// <summary>
    /// Của hàng
    /// </summary>
    public int? IdShop { get; set; }

    /// <summary>
    /// Id cha của đơn tách
    /// </summary>
    public int IdClient { get; set; }

    /// <summary>
    /// Nhóm đơn
    /// </summary>
    public string IdOrderGroup { get; set; }

    public int UserId { get; set; }

    /// <summary>
    /// UserId CTV
    /// </summary>
    public int? IdUserRef { get; set; }

    public int IdRef { get; set; }

    /// <summary>
    /// Mã đơn
    /// </summary>
    public string Code { get; set; }

    /// <summary>
    /// Mã đơn giao vận
    /// </summary>
    public string CodeShip { get; set; }

    /// <summary>
    /// Mã đơn giao vận
    /// </summary>
    public string ShipStatus { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public int? IdProvince { get; set; }

    public int? IdDistrict { get; set; }

    public int? IdWard { get; set; }

    public string Address { get; set; }

    public string Note { get; set; }

    /// <summary>
    /// Tổng tiền hàng
    /// </summary>
    public double? Total { get; set; }

    /// <summary>
    /// Phí vận chuyển
    /// </summary>
    public double? Ship { get; set; }

    /// <summary>
    /// Phí vận chuyển
    /// </summary>
    public double? ShipRoot { get; set; }

    /// <summary>
    /// Giảm giá
    /// </summary>
    public double? Discount { get; set; }

    /// <summary>
    /// Tổng tiền đơn
    /// </summary>
    public double? TotalBill { get; set; }

    /// <summary>
    /// Tiền đặt cọc
    /// </summary>
    public double? Deposit { get; set; }

    /// <summary>
    /// Thưởng từ sản phẩm
    /// </summary>
    public double? ProductReward { get; set; }

    /// <summary>
    /// Thưởng từ đơn trả tiền trước
    /// </summary>
    public double? PrepayReward { get; set; }

    /// <summary>
    /// Thưởng chương trình
    /// </summary>
    public double? PromotionReward { get; set; }

    /// <summary>
    /// Tổng quà tặng
    /// </summary>
    public double? TotalGift { get; set; }

    /// <summary>
    /// Tổng tiền thưởng
    /// </summary>
    public double? TotalReward { get; set; }

    /// <summary>
    /// Tổng tiền thưởng giới thiệu
    /// </summary>
    public double? TotalRewardReferral { get; set; }

    /// <summary>
    /// Phí dapfood
    /// </summary>
    public double? SystemFee { get; set; }

    /// <summary>
    /// Theo chương trình km nào
    /// </summary>
    public int? IdPromotion { get; set; }

    /// <summary>
    /// Đơn chốt
    /// </summary>
    public bool? IsVerified { get; set; }

    /// <summary>
    /// 1: Thành công, 2: Hủy, 0: Nothing
    /// </summary>
    public int? PayStatus { get; set; }

    /// <summary>
    /// Đã trừ tiền đơn trả trước của ctv
    /// </summary>
    public bool? IsPaid { get; set; }

    /// <summary>
    /// Đã trả thưởng cho ctv
    /// </summary>
    public bool? IsPaidReward { get; set; }

    /// <summary>
    /// Trạng thái tác nghiệp hiện tại
    /// </summary>
    public int? IdAction { get; set; }

    /// <summary>
    /// Trạng thái giao hàng hiện tại
    /// </summary>
    public int? IdStatus { get; set; }

    /// <summary>
    /// Trạng thái giao hàng hiện tại
    /// </summary>
    public int? LogisticId { get; set; }

    /// <summary>
    /// Trạng thái giao hàng hiện tại
    /// </summary>
    public string TranportId { get; set; }

    /// <summary>
    /// Trạng thái bán hàng
    /// </summary>
    public string Reason { get; set; }

    /// <summary>
    /// Thanh toán luôn
    /// </summary>
    public bool? IsPrepay { get; set; }

    /// <summary>
    /// Lên đơn trên dapfood
    /// </summary>
    public bool? IsManual { get; set; }

    /// <summary>
    /// Kênh thanh toán: 1 điểm dapfood, 2 ngân lượng
    /// </summary>
    public int? PaymentChannel { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    public bool? IsRated { get; set; }

    /// <summary>
    /// Ngày mong muốn nhận hàng
    /// </summary>
    public DateTime? DeliveryDate { get; set; }

    /// <summary>
    /// Khách hàng tự chốt qua link
    /// </summary>
    public bool? IsCustomerConfirmed { get; set; }

    /// <summary>
    /// Người giới thiệu
    /// </summary>
    public int? UserIdReferencer { get; set; }

    public int? IdPromotionUser { get; set; }

    public int? OrderType { get; set; }

    /// <summary>
    /// Quãng đường
    /// </summary>
    public double? Distance { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public string FullAddress { get; set; }

    public bool? ReceiveAtShop { get; set; }

    public bool? IsInvoiced { get; set; }

    public int? IdInvoice { get; set; }

    public bool? IsInvoice { get; set; }

    public int? IdPromotionUserShip { get; set; }

    public string UtmSource { get; set; }

    public string Voucher { get; set; }

    public double? DiscountShip { get; set; }

    public string BankCode { get; set; }

    /// <summary>
    /// Đơn đặt hàng trước
    /// </summary>
    public bool? IsPreOrder { get; set; }

    /// <summary>
    /// Điểm thưởng tích lũy: tiền hàng * phí hoa hồng trả của sàn
    /// </summary>
    public double? Points { get; set; }

    public int? IdPromotionReward { get; set; }

    public int? IdUserAddress { get; set; }

    /// <summary>
    /// Chiết khấu cho cửa hàng
    /// </summary>
    public double? DiscountShop { get; set; }

    public virtual ICollection<Feedbacks> Feedbacks { get; set; } = new List<Feedbacks>();

    public virtual Actions IdActionNavigation { get; set; }

    public virtual Districts IdDistrictNavigation { get; set; }

    public virtual Invoices IdInvoiceNavigation { get; set; }

    public virtual Promotions IdPromotionNavigation { get; set; }

    public virtual PromotionUsers IdPromotionRewardNavigation { get; set; }

    public virtual PromotionUsers IdPromotionUserNavigation { get; set; }

    public virtual PromotionUsers IdPromotionUserShipNavigation { get; set; }

    public virtual Provinces IdProvinceNavigation { get; set; }

    public virtual Shops IdShopNavigation { get; set; }

    public virtual Status IdStatusNavigation { get; set; }

    public virtual UserAddress IdUserAddressNavigation { get; set; }

    public virtual Wards IdWardNavigation { get; set; }

    public virtual ICollection<OrderActions> OrderActions { get; set; } = new List<OrderActions>();

    public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();

    public virtual ICollection<OrderGifts> OrderGifts { get; set; } = new List<OrderGifts>();

    public virtual ICollection<OrderPromotionUsers> OrderPromotionUsers { get; set; } = new List<OrderPromotionUsers>();

    public virtual ICollection<OrderPromotions> OrderPromotions { get; set; } = new List<OrderPromotions>();

    public virtual ICollection<OrderStatus> OrderStatus { get; set; } = new List<OrderStatus>();

    public virtual ICollection<PromotionUsersGiftcode> PromotionUsersGiftcode { get; set; } = new List<PromotionUsersGiftcode>();

    public virtual Users User { get; set; }
}