// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class OrderGifts
{
    public int Id { get; set; }

    public int IdOrder { get; set; }

    /// <summary>
    /// Loại 1 freeship, 2: mã giảm giá, 3 sản phẩm
    /// </summary>
    public int Type { get; set; }

    public int? IdProduct { get; set; }

    public int? Quantity { get; set; }

    /// <summary>
    /// Mã quà tặng
    /// </summary>
    public int? IdGift { get; set; }

    /// <summary>
    /// Số điểm
    /// </summary>
    public double? Value { get; set; }

    public virtual Gifts IdGiftNavigation { get; set; }

    public virtual Orders IdOrderNavigation { get; set; }

    public virtual Products IdProductNavigation { get; set; }
}