// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class OrderPromotionSales
{
    public int Id { get; set; }

    public int IdOrderSale { get; set; }

    public int IdPromotionSale { get; set; }

    public int IdProduct { get; set; }

    /// <summary>
    /// 1 = % , 2 = điểm
    /// </summary>
    public int? Mode { get; set; }

    public int? Quantity { get; set; }

    public double? Sale { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual SaleOrders IdOrderSaleNavigation { get; set; }

    public virtual PromotionSales IdPromotionSaleNavigation { get; set; }
}