// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class OrderStatus
{
    public int Id { get; set; }

    /// <summary>
    /// Trạng thái giao hàng
    /// </summary>
    public int? IdOrder { get; set; }

    /// <summary>
    /// Trạng thái giao hàng
    /// </summary>
    public int? IdStatus { get; set; }

    public string Name { get; set; }

    public string Note { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Orders IdOrderNavigation { get; set; }

    public virtual Status IdStatusNavigation { get; set; }
}