// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class PartLessions
{
    public int Id { get; set; }

    public int? IdLession { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// thứ tự hiển thị học phần
    /// </summary>
    public int? DisplayPart { get; set; }

    /// <summary>
    /// Tổng thời gian của học phần
    /// </summary>
    public double? TotalTimeVideo { get; set; }

    /// <summary>
    /// Tổng số bài giảng
    /// </summary>
    public int? TotalLesson { get; set; }

    /// <summary>
    /// Sắp xếp thứ tự
    /// </summary>
    public int? Sort { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Lessons IdLessionNavigation { get; set; }

    public virtual ICollection<LessonDetails> LessonDetails { get; set; } = new List<LessonDetails>();
}