// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Permissions
{
    public int Id { get; set; }

    public string Service { get; set; }

    public string Controller { get; set; }

    public string Permission { get; set; }

    public int? Index { get; set; }

    public string Description { get; set; }

    public int? ControllerId { get; set; }

    public virtual AppController AppController { get; set; }
}