// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Points
{
    public int Id { get; set; }

    /// <summary>
    /// Nội dung chuyển khoản random
    /// </summary>
    public string Code { get; set; }

    public int UserId { get; set; }

    /// <summary>
    /// Số tiền giao dịch
    /// </summary>
    public double? Deal { get; set; }

    public int? Fee { get; set; }

    public int? Tax { get; set; }

    /// <summary>
    /// Loại giao dịch: Nạp tiền và rút tiền
    /// </summary>
    public int? DealType { get; set; }

    /// <summary>
    /// Hình thức thanh toán: 1 Ngân lượng, 2 thủ công
    /// </summary>
    public int? Payment { get; set; }

    /// <summary>
    /// Ngân lượng: 1 thanh toán luôn, 2 tạm giữ
    /// </summary>
    public int? PaymentType { get; set; }

    /// <summary>
    /// Ngân lượng: Mã giao dịch tại NgânLượng.vn
    /// </summary>
    public int? PaymentId { get; set; }

    /// <summary>
    /// Ngân lượng: Thông tin về giao dịch, Giá trị do website gửi sang
    /// </summary>
    public string TransactionInfo { get; set; }

    /// <summary>
    /// Ngân lượng: Chuỗi mã hóa
    /// </summary>
    public string SecureCode { get; set; }

    /// <summary>
    /// Ngân lượng: Giao dịch thanh toán có bị lỗi hay không. $error_text == &quot;&quot; là không có lỗi. Nếu có lỗi, mô tả lỗi được chứa trong $error_text
    /// </summary>
    public int? ErrorText { get; set; }

    /// <summary>
    /// Id ngân hàng
    /// </summary>
    public int? IdBank { get; set; }

    /// <summary>
    /// Mã ngân hàng
    /// </summary>
    public string BankCode { get; set; }

    /// <summary>
    /// tên chủ thẻ k đc để trống
    /// </summary>
    public string CardFullname { get; set; }

    /// <summary>
    /// max 20 kí tự
    /// </summary>
    public string CardNumber { get; set; }

    /// <summary>
    /// Mã tham chiếu do website bán hàng sinh ra ( nhỏ hơn 500 kí tự)
    /// </summary>
    public string RefCode { get; set; }

    /// <summary>
    /// Hình thức rút. -Rút về thẻ ATM nhận giá trị 2 -Rút về tài khoản ngân hàng nhận giá trị 3
    /// </summary>
    public int? AccountType { get; set; }

    /// <summary>
    /// Mã giao dịch rút tiền tại NganLuong.vn
    /// </summary>
    public string TransactionId { get; set; }

    /// <summary>
    /// 00 - Đã thành công; 01 - Đang chờ xử lý; 02 - Không thành công
    /// </summary>
    public string TransactionStatus { get; set; }

    /// <summary>
    /// Mã lỗi
    /// </summary>
    public string ErrorCode { get; set; }

    public string AccountIdentify { get; set; }

    public string BankNote { get; set; }

    public string Note { get; set; }

    /// <summary>
    /// 0: Chưa xử lý; 1: Thành công; 2: Đang xử lý; 3: Hủy; 4: Lỗi
    /// </summary>
    public int? Status { get; set; }

    /// <summary>
    /// Lưu lại id của bản ghi trước khi giao dịch không thành công
    /// </summary>
    public int? IdRef { get; set; }

    /// <summary>
    /// Tiền khả dụng (nghĩa là không đóng băng)
    /// </summary>
    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual DealTypes DealTypeNavigation { get; set; }

    public virtual Banks IdBankNavigation { get; set; }
}