// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class ProductCombos
{
    public int Id { get; set; }

    public int IdProduct { get; set; }

    public int? Quantity { get; set; }

    public double? Price { get; set; }

    /// <summary>
    /// 1. Hàng bán, 2. Quà tặng
    /// </summary>
    public bool? IsGift { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public short? Sort { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    /// <summary>
    /// Sản phẩm con của combo
    /// </summary>
    public int IdProductCombo { get; set; }

    public virtual Products IdProductNavigation { get; set; }
}