// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class ProductCategories
{
    public int Id { get; set; }

    public int IdCategory { get; set; }

    public int IdProduct { get; set; }
}