// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Products
{
    public int Id { get; set; }

    public int IdRef { get; set; }

    public int IdClient { get; set; }

    /// <summary>
    /// Xuất xứ
    /// </summary>
    public int? IdCountry { get; set; }

    public int? IdBrand { get; set; }

    /// <summary>
    /// Nhà Cung cấp
    /// </summary>
    public int? IdSupplier { get; set; }

    public int? IdCategory { get; set; }

    public int? IdCategory1 { get; set; }

    public int? IdCategory2 { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// Giá bán lẻ
    /// </summary>
    public double? Price { get; set; }

    /// <summary>
    /// giá bán sỉ
    /// </summary>
    public double? PriceWholesale { get; set; }

    public double? Weight { get; set; }

    public double? WeightGram { get; set; }

    public double? Height { get; set; }

    public double? Width { get; set; }

    public double? Length { get; set; }

    public double? Quantity { get; set; }

    /// <summary>
    /// Hoa hồng
    /// </summary>
    public double? Reward { get; set; }

    /// <summary>
    /// Mô tả
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string ListImages { get; set; }

    /// <summary>
    /// 1: Gửi duyệt, 2 Đã duyệt, 3 Không Duyệt
    /// </summary>
    public int? StatusApprove { get; set; }

    /// <summary>
    /// Tin nhắn duyệt
    /// </summary>
    public string MessageApprove { get; set; }

    public bool? IsAdminApprove { get; set; }

    public bool? IsApproved { get; set; }

    public bool? IsActive { get; set; }

    /// <summary>
    /// Đánh giá để sắp xếp sản phẩm
    /// </summary>
    public int? Rate { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string BusinessLicense { get; set; }

    /// <summary>
    /// Chính sách cho ctv
    /// </summary>
    public string PolicyCtv { get; set; }

    /// <summary>
    /// Mô tả
    /// </summary>
    public string Detail { get; set; }

    /// <summary>
    /// Chính sách cho ctv
    /// </summary>
    public string Video1 { get; set; }

    /// <summary>
    /// Chính sách cho ctv
    /// </summary>
    public string VideoTitle1 { get; set; }

    /// <summary>
    /// Chính sách cho ctv
    /// </summary>
    public string Video2 { get; set; }

    /// <summary>
    /// Chính sách cho ctv
    /// </summary>
    public string VideoTitle2 { get; set; }

    /// <summary>
    /// Cho điểm để xếp top 1 hay 2
    /// </summary>
    public int? Rank { get; set; }

    /// <summary>
    /// 5* =&gt; 5 điểm, 4* =&gt; 3 điểm, 3* =&gt; 0 điểm, 2* =&gt; 5 điểm, 1* =&gt; 10 điểm
    /// </summary>
    public int? Point { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    /// <summary>
    /// Ngày trạng thay đổi trạng thái đơn hàng
    /// </summary>
    public DateTime? OrderDate { get; set; }

    /// <summary>
    /// Ngày bắt đầu mong muốn nhận hàng
    /// </summary>
    public int? PreOrderDate { get; set; }

    /// <summary>
    /// Hết hàng
    /// </summary>
    public bool? IsSoldOut { get; set; }

    /// <summary>
    /// Thời gian giao hàng trung bình
    /// </summary>
    public double? ShipTimeAvg { get; set; }

    public int? SaleQuantity { get; set; }

    public double? SumRate { get; set; }

    public int? CountRate { get; set; }

    public int? CountComment { get; set; }

    public int? Tax { get; set; }

    public string Unit { get; set; }

    /// <summary>
    /// Có cho phép đặt hàng trước hay không?
    /// </summary>
    public bool? IsPreOrder { get; set; }

    public string TitleSeo { get; set; }

    public string DescriptionSeo { get; set; }

    /// <summary>
    /// Loại sản phẩm 1 or null:  Sản phẩm bán hàng, 2: Combo, 3: Quà tặng
    /// </summary>
    public short? Type { get; set; }

    /// <summary>
    /// Điểm thưởng theo sản phẩm của doanh nghiệp
    /// </summary>
    public double? PointClient { get; set; }

    /// <summary>
    /// Sản phẩm có sử dụng cho GTMT hay ko?
    /// </summary>
    public bool? IsGtmt { get; set; }

    /// <summary>
    /// Mã sản phẩm bên thứ 3 (cukcuk)
    /// </summary>
    public string IdSyn { get; set; }

    public double? Discount { get; set; }

    /// <summary>
    /// Hiển thị theo loại khách hàng
    /// </summary>
    public string ShowUserType { get; set; }

    public virtual ICollection<Contents> Contents { get; set; } = new List<Contents>();

    public virtual ICollection<Feeds> Feeds { get; set; } = new List<Feeds>();

    public virtual ICollection<FoodProducts> FoodProducts { get; set; } = new List<FoodProducts>();

    public virtual Brands IdBrandNavigation { get; set; }

    public virtual Categories IdCategoryNavigation { get; set; }

    public virtual Clients IdClientNavigation { get; set; }

    public virtual Countries IdCountryNavigation { get; set; }

    public virtual Suppliers IdSupplierNavigation { get; set; }

    public virtual ICollection<LessionProducts> LessionProducts { get; set; } = new List<LessionProducts>();

    public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();

    public virtual ICollection<OrderGifts> OrderGifts { get; set; } = new List<OrderGifts>();

    public virtual ICollection<ProductCombos> ProductCombos { get; set; } = new List<ProductCombos>();

    public virtual ICollection<ProductProvinces> ProductProvinces { get; set; } = new List<ProductProvinces>();

    public virtual ICollection<ProductRegs> ProductRegs { get; set; } = new List<ProductRegs>();

    public virtual ICollection<PromotionProducts> PromotionProducts { get; set; } = new List<PromotionProducts>();

    public virtual ICollection<PromotionSaleProducts> PromotionSaleProducts { get; set; } = new List<PromotionSaleProducts>();

    public virtual ICollection<PromotionSalesGiftProducts> PromotionSalesGiftProducts { get; set; } = new List<PromotionSalesGiftProducts>();

    public virtual ICollection<PromotionUserProducts> PromotionUserProducts { get; set; } = new List<PromotionUserProducts>();

    public virtual ICollection<PromotionUsersGiftProducts> PromotionUsersGiftProducts { get; set; } = new List<PromotionUsersGiftProducts>();

    public virtual ICollection<SaleOrderDetails> SaleOrderDetails { get; set; } = new List<SaleOrderDetails>();

    public virtual ICollection<ShopInOutDetails> ShopInOutDetails { get; set; } = new List<ShopInOutDetails>();

    public virtual ICollection<ShopProducts> ShopProducts { get; set; } = new List<ShopProducts>();

    public virtual ICollection<WarehouseHistories> WarehouseHistories { get; set; } = new List<WarehouseHistories>();

    public virtual ICollection<WarehouseInOutDetails> WarehouseInOutDetails { get; set; } = new List<WarehouseInOutDetails>();

    public virtual ICollection<WarehouseProducts> WarehouseProducts { get; set; } = new List<WarehouseProducts>();
}