// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class ProductLogs
{
    public int Id { get; set; }

    public int IdProduct { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public double? Price { get; set; }

    public double? Weight { get; set; }

    public double? WeightGram { get; set; }

    public double? Quantity { get; set; }

    public double? Reward { get; set; }

    /// <summary>
    /// 1: Gửi duyệt, 2 Đã duyệt, 3 Không Duyệt
    /// </summary>
    public int? StatusApprove { get; set; }

    /// <summary>
    /// Tin nhắn duyệt
    /// </summary>
    public string MessageApprove { get; set; }

    public bool? IsAdminApprove { get; set; }

    public bool? IsApproved { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    /// <summary>
    /// Hết hàng
    /// </summary>
    public bool? IsSoldOut { get; set; }
}