// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class ProductRegs
{
    public int Id { get; set; }

    public int? IdClient { get; set; }

    public int UserId { get; set; }

    public int? IdProduct { get; set; }

    /// <summary>
    /// Yêu thích
    /// </summary>
    public bool? IsFavorite { get; set; }

    /// <summary>
    /// Tổng thưởng
    /// </summary>
    public double? Reward { get; set; }

    /// <summary>
    /// Tổng doanh số
    /// </summary>
    public double? TotalSales { get; set; }

    /// <summary>
    /// Số lượng bán
    /// </summary>
    public int? CountSales { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    /// <summary>
    /// Link
    /// </summary>
    public string Url { get; set; }

    public string Rename { get; set; }

    /// <summary>
    /// Linkvideo
    /// </summary>
    public string LinkVideo { get; set; }

    /// <summary>
    /// Thứ tự
    /// </summary>
    public int? Sort { get; set; }

    /// <summary>
    /// Tổng số click
    /// </summary>
    public int? TotalClick { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Products IdProductNavigation { get; set; }

    public virtual Users User { get; set; }
}