// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class PromotionUserNotIns
{
    public int Id { get; set; }

    public int IdPromotionUser { get; set; }

    public int IdPromotionUserRef { get; set; }

    public virtual PromotionUsers IdPromotionUserNavigation { get; set; }
}