// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class PromotionSaleNotIns
{
    public int Id { get; set; }

    public int IdPromotionSale { get; set; }

    public int IdPromotionSaleRef { get; set; }

    public virtual PromotionSales IdPromotionSaleNavigation { get; set; }
}