// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class PromotionUsersGiftcode
{
    public int Id { get; set; }

    public string Code { get; set; }

    public int? UserId { get; set; }

    public bool? IsActived { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public int? IdOrder { get; set; }

    public int IdPromotionUser { get; set; }

    public virtual Orders IdOrderNavigation { get; set; }

    public virtual PromotionUsers IdPromotionUserNavigation { get; set; }
}