// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Promotions
{
    public int Id { get; set; }

    public int? IdClient { get; set; }

    /// <summary>
    /// Hình thức khuyến mãi
    /// </summary>
    public int? Type { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    /// <summary>
    /// Ngày bắt đầu
    /// </summary>
    public DateTime? StartDate { get; set; }

    /// <summary>
    /// Ngày kết thúc
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Số lượng khuyến mãi
    /// </summary>
    public int? Quantity { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// Giá trị đơn từ
    /// </summary>
    public double? FromValue { get; set; }

    /// <summary>
    /// đến
    /// </summary>
    public double? ToValue { get; set; }

    /// <summary>
    /// 1 = % , 2 = điểm
    /// </summary>
    public int? Mode { get; set; }

    /// <summary>
    /// value khuyến mãi
    /// </summary>
    public double? Sale { get; set; }

    /// <summary>
    /// Tối đa
    /// </summary>
    public double? MaxValue { get; set; }

    /// <summary>
    /// Số lần mỗi user được km
    /// </summary>
    public int? NumberPerUser { get; set; }

    /// <summary>
    /// Số sản phẩm mỗi user được km
    /// </summary>
    public int? NumberProductPerUser { get; set; }

    public int? Sort { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public int? PaymentMethod { get; set; }

    public virtual ICollection<OrderPromotions> OrderPromotions { get; set; } = new List<OrderPromotions>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public virtual ICollection<PromotionNotIns> PromotionNotIns { get; set; } = new List<PromotionNotIns>();

    public virtual ICollection<PromotionProducts> PromotionProducts { get; set; } = new List<PromotionProducts>();
}