// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class PromotionProducts
{
    public int Id { get; set; }

    public int IdPromotion { get; set; }

    public int IdProduct { get; set; }

    public double? Sale { get; set; }

    public string Mode { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public virtual Products IdProductNavigation { get; set; }

    public virtual Promotions IdPromotionNavigation { get; set; }
}