// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class PromotionUsers
{
    public int Id { get; set; }

    public int? IdClient { get; set; }

    /// <summary>
    /// Hình thức khuyến mãi
    /// </summary>
    public int? Type { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    /// <summary>
    /// Ngày bắt đầu
    /// </summary>
    public DateTime? StartDate { get; set; }

    /// <summary>
    /// Ngày kết thúc
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Số lượng khuyến mãi
    /// </summary>
    public int? Quantity { get; set; }

    public string Description { get; set; }

    public string ShortDescription { get; set; }

    /// <summary>
    /// Giá trị đơn từ
    /// </summary>
    public double? FromValue { get; set; }

    /// <summary>
    /// đến
    /// </summary>
    public double? ToValue { get; set; }

    /// <summary>
    /// 1 = % , 2 = điểm
    /// </summary>
    public int? Mode { get; set; }

    /// <summary>
    /// value khuyến mãi
    /// </summary>
    public double? Sale { get; set; }

    /// <summary>
    /// Tối đa
    /// </summary>
    public double? MaxValue { get; set; }

    /// <summary>
    /// Số lần mỗi user được km
    /// </summary>
    public int? NumberPerUser { get; set; }

    /// <summary>
    /// Số sản phẩm mỗi user được km
    /// </summary>
    public int? NumberProductPerUser { get; set; }

    public int? Sort { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public double? MaxSale { get; set; }

    public string PaymentMethod { get; set; }

    public string ImageWeb { get; set; }

    public int? ReferralUserId { get; set; }

    public int? QuantityProduct { get; set; }

    /// <summary>
    /// Người dùng tạo đơn mới
    /// </summary>
    public bool? IsFirstOrderUser { get; set; }

    /// <summary>
    /// Danh mục sản phẩm được khuyến mãi
    /// </summary>
    public int? IdCategory { get; set; }

    /// <summary>
    /// Danh mục cấp 2 khuyến mãi
    /// </summary>
    public int? IdCategory1 { get; set; }

    /// <summary>
    /// Mã nhà cung cấp được khuyến mãi
    /// </summary>
    public int? IdSupplier { get; set; }

    /// <summary>
    /// Nếu True thì: Tiền giảm của đơn sẽ thành tiền thưởng của CTV
    /// </summary>
    public bool? IsReward { get; set; }

    public DateTime? StartDateReward { get; set; }

    public DateTime? EndDateReward { get; set; }

    /// <summary>
    /// Cấp bậc tài khoản
    /// </summary>
    public int? IdLevel { get; set; }

    /// <summary>
    /// Có sử dụng cho Gtmt ko?
    /// </summary>
    public bool? IsGtmt { get; set; }

    /// <summary>
    /// Hiển thị cho loại khách
    /// </summary>
    public string ShowUserType { get; set; }

    public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();

    public virtual ICollection<OrderPromotionUsers> OrderPromotionUsers { get; set; } = new List<OrderPromotionUsers>();

    public virtual ICollection<Orders> OrdersIdPromotionRewardNavigation { get; set; } = new List<Orders>();

    public virtual ICollection<Orders> OrdersIdPromotionUserNavigation { get; set; } = new List<Orders>();

    public virtual ICollection<Orders> OrdersIdPromotionUserShipNavigation { get; set; } = new List<Orders>();

    public virtual ICollection<PromotionUserLevels> PromotionUserLevels { get; set; } = new List<PromotionUserLevels>();

    public virtual ICollection<PromotionUserNotIns> PromotionUserNotIns { get; set; } = new List<PromotionUserNotIns>();

    public virtual ICollection<PromotionUserProducts> PromotionUserProducts { get; set; } = new List<PromotionUserProducts>();

    public virtual ICollection<PromotionUsersGiftProducts> PromotionUsersGiftProducts { get; set; } = new List<PromotionUsersGiftProducts>();

    public virtual ICollection<PromotionUsersGiftcode> PromotionUsersGiftcode { get; set; } = new List<PromotionUsersGiftcode>();
}