// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class PromotionSalesGiftcode
{
    public int Id { get; set; }

    public string Code { get; set; }

    public int? UserId { get; set; }

    public bool? IsActived { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public int? IdOrderSale { get; set; }

    public int IdPromotionSale { get; set; }

    public virtual SaleOrders IdOrderSaleNavigation { get; set; }

    public virtual PromotionSales IdPromotionSaleNavigation { get; set; }
}