// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class PromotionNotIns
{
    public int Id { get; set; }

    public int IdPromotion { get; set; }

    public int IdPromotionRef { get; set; }

    public virtual Promotions IdPromotionNavigation { get; set; }
}