// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class PromotionUserLevels
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double? FromValue { get; set; }

    public double? ToValue { get; set; }

    public double? Reward { get; set; }

    public bool? IsPercent { get; set; }

    public bool? IsActive { get; set; }

    public int? IdPromotionUser { get; set; }

    public virtual PromotionUsers IdPromotionUserNavigation { get; set; }
}