// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class PromotionSales
{
    public int Id { get; set; }

    public int? IdClient { get; set; }

    /// <summary>
    /// Hình thức khuyến mãi
    /// </summary>
    public int? Type { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    /// <summary>
    /// Ngày bắt đầu
    /// </summary>
    public DateTime? StartDate { get; set; }

    /// <summary>
    /// Ngày kết thúc
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Số lượng khuyến mãi
    /// </summary>
    public int? Quantity { get; set; }

    public string Description { get; set; }

    public string ShortDescription { get; set; }

    /// <summary>
    /// Giá trị đơn từ
    /// </summary>
    public double? FromValue { get; set; }

    /// <summary>
    /// đến
    /// </summary>
    public double? ToValue { get; set; }

    /// <summary>
    /// 1 = % , 2 = điểm
    /// </summary>
    public int? Mode { get; set; }

    /// <summary>
    /// value khuyến mãi
    /// </summary>
    public double? Sale { get; set; }

    /// <summary>
    /// Tối đa
    /// </summary>
    public double? MaxValue { get; set; }

    /// <summary>
    /// Số lần mỗi user được km
    /// </summary>
    public int? NumberPerUser { get; set; }

    /// <summary>
    /// Số sản phẩm mỗi user được km
    /// </summary>
    public int? NumberProductPerUser { get; set; }

    public int? Sort { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public double? MaxSale { get; set; }

    public int? PaymentMethod { get; set; }

    public string ImageWeb { get; set; }

    public int? ReferralUserId { get; set; }

    public int? QuantityProduct { get; set; }

    /// <summary>
    /// Người dùng tạo đơn mới
    /// </summary>
    public bool? IsFirstOrderUser { get; set; }

    /// <summary>
    /// Danh mục sản phẩm được khuyến mãi
    /// </summary>
    public int? IdCategory { get; set; }

    /// <summary>
    /// Danh mục cấp 2 khuyến mãi
    /// </summary>
    public int? IdCategory1 { get; set; }

    /// <summary>
    /// Mã nhà cung cấp được khuyến mãi
    /// </summary>
    public int? IdSupplier { get; set; }

    /// <summary>
    /// Nếu True thì: Tiền giảm của đơn sẽ thành tiền thưởng của CTV
    /// </summary>
    public bool? IsReward { get; set; }

    public DateTime? StartDateReward { get; set; }

    public DateTime? EndDateReward { get; set; }

    /// <summary>
    /// Cấp bậc tài khoản
    /// </summary>
    public int? IdLevel { get; set; }

    /// <summary>
    /// Có sử dụng cho Gtmt ko?
    /// </summary>
    public bool? IsGtmt { get; set; }

    public virtual ICollection<OrderPromotionSales> OrderPromotionSales { get; set; } = new List<OrderPromotionSales>();

    public virtual ICollection<PromotionSaleNotIns> PromotionSaleNotIns { get; set; } = new List<PromotionSaleNotIns>();

    public virtual ICollection<PromotionSaleProducts> PromotionSaleProducts { get; set; } = new List<PromotionSaleProducts>();

    public virtual ICollection<PromotionSalesGiftProducts> PromotionSalesGiftProducts { get; set; } = new List<PromotionSalesGiftProducts>();

    public virtual ICollection<PromotionSalesGiftcode> PromotionSalesGiftcode { get; set; } = new List<PromotionSalesGiftcode>();

    public virtual ICollection<SaleOrderDetails> SaleOrderDetails { get; set; } = new List<SaleOrderDetails>();

    public virtual ICollection<SaleOrders> SaleOrdersIdPromotionRewardNavigation { get; set; } = new List<SaleOrders>();

    public virtual ICollection<SaleOrders> SaleOrdersIdPromotionSaleNavigation { get; set; } = new List<SaleOrders>();

    public virtual ICollection<SaleOrders> SaleOrdersIdPromotionSaleShipNavigation { get; set; } = new List<SaleOrders>();
}