// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Provinces
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int? IdRegions { get; set; }

    public bool? IsSellApp { get; set; }

    public bool? IsSellDefault { get; set; }

    public bool? IsSellOffline { get; set; }

    public virtual ICollection<Districts> Districts { get; set; } = new List<Districts>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public virtual ICollection<ProductProvinces> ProductProvinces { get; set; } = new List<ProductProvinces>();

    public virtual ICollection<SaleOrders> SaleOrders { get; set; } = new List<SaleOrders>();

    public virtual ICollection<Wards> Wards { get; set; } = new List<Wards>();
}