// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class SaleOrderStatus
{
    public int Id { get; set; }

    /// <summary>
    /// Trạng thái giao hàng
    /// </summary>
    public int? IdSaleOrder { get; set; }

    /// <summary>
    /// Trạng thái giao hàng
    /// </summary>
    public int? IdSaleStatus { get; set; }

    public string Note { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual SaleOrders IdSaleOrderNavigation { get; set; }

    public virtual SaleStatus IdSaleStatusNavigation { get; set; }
}