// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class SaleOrderDetails
{
    public int Id { get; set; }

    public int IdSaleOrder { get; set; }

    public int IdProduct { get; set; }

    public int IdProductRef { get; set; }

    public int? Quantity { get; set; }

    /// <summary>
    /// Giá bán tại thời điểm
    /// </summary>
    public double? PriceWholesale { get; set; }

    /// <summary>
    /// Tích lũy sản phẩm
    /// </summary>
    public double? Points { get; set; }

    /// <summary>
    /// Tiền thưởng
    /// </summary>
    public double? Reward { get; set; }

    public double? Rating { get; set; }

    public string Comment { get; set; }

    public string CommentImages { get; set; }

    /// <summary>
    /// Level tại thời diểm lên đơn của ctv
    /// </summary>
    public int? Level { get; set; }

    /// <summary>
    /// Doanh số tại thời điểm lên đơn của CTV
    /// </summary>
    public double? TotalSale { get; set; }

    /// <summary>
    /// Thưởng người giới thiệu
    /// </summary>
    public double? RewardReferencer { get; set; }

    public DateTime? DateRating { get; set; }

    public string UserRating { get; set; }

    public int? IdPromotionSale { get; set; }

    public double? Discount { get; set; }

    /// <summary>
    /// Trạng thái đơn hàng hiện tại
    /// </summary>
    public int? IdStatus { get; set; }

    /// <summary>
    /// Ghi chú
    /// </summary>
    public string Note { get; set; }

    public int? UserId { get; set; }

    public virtual Products IdProductNavigation { get; set; }

    public virtual PromotionSales IdPromotionSaleNavigation { get; set; }

    public virtual SaleOrders IdSaleOrderNavigation { get; set; }
}