// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class SaleActions
{
    public int Id { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// Tác nghiệp trước
    /// </summary>
    public string Actions { get; set; }

    /// <summary>
    /// Tác nghiệp trước
    /// </summary>
    public string StatusActions { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string Roles { get; set; }

    public virtual ICollection<SaleOrderActions> SaleOrderActions { get; set; } = new List<SaleOrderActions>();

    public virtual ICollection<SaleOrders> SaleOrders { get; set; } = new List<SaleOrders>();
}