// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Settings
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string Data { get; set; }
}