// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

/// <summary>
/// Địa chỉ giao hàng khi sale tạo đơn khi Đại lý không có tài khoản
/// </summary>
public partial class ShippingAddress
{
    public int Id { get; set; }

    public int IdSale { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public int? IdProvince { get; set; }

    public int? IdDistrict { get; set; }

    public int? IdWard { get; set; }

    public string Address { get; set; }

    public int? IdType { get; set; }

    public bool? IsDefault { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public virtual Users IdSaleNavigation { get; set; }
}