// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

/// <summary>
/// Bảng danh sách dịch vụ vận chuyển
/// </summary>
public partial class ShippingServices
{
    public int Id { get; set; }

    /// <summary>
    /// Id doanh nghiệp
    /// </summary>
    public int? IdClient { get; set; }

    /// <summary>
    /// Token sử dụng dịch vụ vận chuyển
    /// </summary>
    public string Token { get; set; }

    public int? TypeDelivery { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }
}