// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class ShopProducts
{
    public int Id { get; set; }

    public int? IdClient { get; set; }

    public int? IdShop { get; set; }

    public int? IdProduct { get; set; }

    /// <summary>
    /// Số lượng tồn tại trong kho
    /// </summary>
    public int? Quantity { get; set; }

    /// <summary>
    /// Số lượng cảnh báo nhập hàng
    /// </summary>
    public int? QuantityMin { get; set; }

    /// <summary>
    /// Thứ tự
    /// </summary>
    public int? Sort { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Products IdProductNavigation { get; set; }

    public virtual Shops IdShopNavigation { get; set; }
}