// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Shops
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int? UserId { get; set; }

    public int? IdClient { get; set; }

    /// <summary>
    /// Thuoc kho nao
    /// </summary>
    public int? IdDc { get; set; }

    public int? IdProvince { get; set; }

    public int? IdDistrict { get; set; }

    public int? IdWard { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    /// <summary>
    /// Thứ tự
    /// </summary>
    public int? Sort { get; set; }

    /// <summary>
    /// Kho phan phoi
    /// </summary>
    public bool? IsDc { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string Avatar { get; set; }

    public string Description { get; set; }

    public string FullAddress { get; set; }

    public string IdWards { get; set; }

    public int? CountOrdersAction { get; set; }

    public bool? IsShopBabi { get; set; }

    public bool? IsOpen { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public bool? IsShow { get; set; }

    public int? IdTypeShop { get; set; }

    public string NoteShip { get; set; }

    public bool? NeverSellOnline { get; set; }

    public string AddressShow { get; set; }

    public bool? UseLocationShip { get; set; }

    public bool? IsShowBapimi { get; set; }

    public virtual ICollection<DeliveryShops> DeliveryShops { get; set; } = new List<DeliveryShops>();

    public virtual Clients IdClientNavigation { get; set; }

    public virtual ICollection<OrderActions> OrderActions { get; set; } = new List<OrderActions>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public virtual ICollection<ShopProducts> ShopProducts { get; set; } = new List<ShopProducts>();

    public virtual Users User { get; set; }

    public virtual ICollection<UserAddressShopLocations> UserAddressShopLocations { get; set; } = new List<UserAddressShopLocations>();
}