// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class ShopHistories
{
    public int Id { get; set; }

    /// <summary>
    /// Mã tham chiếu:1 operations
    /// </summary>
    public int? IdObject { get; set; }

    public int? IdClient { get; set; }

    public int? IdShop { get; set; }

    /// <summary>
    /// Loai hành động nhập, xuất,...
    /// </summary>
    public int? IdShopOperation { get; set; }

    public int? IdProduct { get; set; }

    public int? Quantity { get; set; }

    public int? IdOrder { get; set; }

    public string OrderCode { get; set; }

    public int? IdOrderOffline { get; set; }

    public string OrderCodeOffline { get; set; }

    public string Descriptions { get; set; }

    /// <summary>
    /// 1: Nhậ; 2: Xuất
    /// </summary>
    public int? Type { get; set; }

    public int? IdProductUnitConvert { get; set; }

    public int? IdProductUnitConvertValue { get; set; }

    public bool? IsAuto { get; set; }

    public bool? IsProcessed { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int? QuantityInventory { get; set; }
}