// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class ShopInOuts
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// Ngày yêu cầu
    /// </summary>
    public DateTime? DateRequest { get; set; }

    public int? IdClient { get; set; }

    /// <summary>
    /// 1: tạo mới, 2: đã chốt, 3 hủy
    /// </summary>
    public int? IdInOutStatus { get; set; }

    public int? IdShop { get; set; }

    public int? IdOrder { get; set; }

    public string Descriptions { get; set; }

    public int? IdShopOperation { get; set; }

    /// <summary>
    /// 1: Nhập hàng; 2: Xuất hàng
    /// </summary>
    public int? Type { get; set; }

    public string Note { get; set; }

    public bool? IsProcessed { get; set; }

    /// <summary>
    /// Shop xác nhận đã nhận hàng
    /// </summary>
    public int? IdShopAccept { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ShopOperations IdShopOperationNavigation { get; set; }

    public virtual ICollection<ShopInOutDetails> ShopInOutDetails { get; set; } = new List<ShopInOutDetails>();
}