// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

/// <summary>
/// 1: Đơn hàng, 2 Giao dịch tài khoản
/// </summary>
public partial class Statements
{
    public int Id { get; set; }

    /// <summary>
    /// Lưu lại id của bản ghi trước khi giao dịch không thành công
    /// </summary>
    public int? IdRef { get; set; }

    /// <summary>
    /// Người chuyển
    /// </summary>
    public int? FromUserId { get; set; }

    public int UserId { get; set; }

    /// <summary>
    /// Số dư trước giao dịch
    /// </summary>
    public double? BalanceBefore { get; set; }

    /// <summary>
    /// Số tiền giao dịch
    /// </summary>
    public double? Deal { get; set; }

    /// <summary>
    /// Số dư
    /// </summary>
    public double? Balance { get; set; }

    /// <summary>
    /// 0: Chưa xử lý; 1: Thành công; 2: Đang xử lý; 3: Hủy; 4: Lỗi
    /// </summary>
    public int? Status { get; set; }

    public string Note { get; set; }

    /// <summary>
    /// Loại giao dịch
    /// </summary>
    public int? Type { get; set; }

    /// <summary>
    /// Lưu lại id của đơn
    /// </summary>
    public int? ObjectId { get; set; }

    /// <summary>
    /// Loại giao dịch
    /// </summary>
    public int? DealType { get; set; }

    /// <summary>
    /// Tiền khả dụng (nghĩa là không đóng băng)
    /// </summary>
    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual DealTypes DealTypeNavigation { get; set; }
}