// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Status
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string NameRef { get; set; }

    /// <summary>
    /// Tác nghiệp trước
    /// </summary>
    public string Actions { get; set; }

    /// <summary>
    /// Phân quyền cho các role được hiển thị tác nghiệp
    /// </summary>
    public string Roles { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int? Sort { get; set; }

    public virtual ICollection<OrderStatus> OrderStatus { get; set; } = new List<OrderStatus>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();
}