// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Suppliers
{
    public int Id { get; set; }

    public int? IdClient { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public int? IdProvince { get; set; }

    public int? IdDistrict { get; set; }

    public int? IdWard { get; set; }

    public string Address { get; set; }

    public string Address2 { get; set; }

    public string Descriptions { get; set; }

    public int? FaxNumber { get; set; }

    public int? TaxCode { get; set; }

    public string Website { get; set; }

    /// <summary>
    /// Nhân viên phục trách
    /// </summary>
    public int? StaffInCharge { get; set; }

    /// <summary>
    /// 0: Chờ duyệt, 1: đã duyệt, 2: hủy, 3 từ chối
    /// </summary>
    public bool? IsActive { get; set; }

    public int? Sort { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Clients IdClientNavigation { get; set; }

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();

    public virtual Users StaffInChargeNavigation { get; set; }
}