// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class TagMaps
{
    public int Id { get; set; }

    public int? ObjectId { get; set; }

    public int? TagId { get; set; }

    /// <summary>
    /// 1: tin tức, 2: sản phẩm, 3: bệnh học, 4: Bài giảng
    /// </summary>
    public int? Type { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Tags Tag { get; set; }
}