// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Tags
{
    public int Id { get; set; }

    public string TagName { get; set; }

    public string Image { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    /// <summary>
    /// Hiển thị danh sách sản phẩm theo mục ở trang chủ AppHome
    /// </summary>
    public bool? IsShowHome { get; set; }

    /// <summary>
    /// Hiển thị trong danh sách
    /// </summary>
    public bool? IsShowList { get; set; }

    /// <summary>
    /// Hiển thị trong danh sách
    /// </summary>
    public bool? IsShowDetail { get; set; }

    /// <summary>
    /// Kiểu hiển thị: 1 Chỉ avartar, 2 Full: Avatar + Name + &apos;,&apos; +3: màu sắc: ví dụ: &apos;1,#0e1983&apos;
    /// </summary>
    public int? ShowType { get; set; }

    public virtual ICollection<TagMaps> TagMaps { get; set; } = new List<TagMaps>();
}