// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class TempTable
{
    public int? IdParent { get; set; }

    public string Code { get; set; }

    public int? IdClient { get; set; }

    public int? IdLevel { get; set; }

    public int? IdType { get; set; }

    public string Avatar { get; set; }

    public string UserName { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Cmt { get; set; }

    public string CmtFront { get; set; }

    public string CmtBackside { get; set; }

    public bool? IsApproveCmt { get; set; }

    public string Protocol { get; set; }

    public string Domain { get; set; }

    public int? DomainStatus { get; set; }

    public string FacebookId { get; set; }

    public string FacebookName { get; set; }

    public string Email { get; set; }

    public double? Balance { get; set; }

    public double? CashInTransit { get; set; }

    public double? TotalReward { get; set; }

    public int? IdAddress { get; set; }

    public int? IdProvince { get; set; }

    public int? IdDistrict { get; set; }

    public int? IdWard { get; set; }

    public string Address { get; set; }

    public int? IdBank { get; set; }

    public string BankBranch { get; set; }

    public string BankFullName { get; set; }

    public string BankNumber { get; set; }

    public string BankCardNumber { get; set; }

    public bool? IsTrial { get; set; }

    public bool? IsLogout { get; set; }

    public bool? IsLocked { get; set; }

    public bool? IsApproved { get; set; }

    public int? IdSupport { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int? ReferralUserId { get; set; }

    public string ReferralCode { get; set; }

    public bool? IsAdminClient { get; set; }

    public int? IdShop { get; set; }

    public bool? RequestCancel { get; set; }

    public DateTime? RequestCancelDate { get; set; }

    public bool? Gender { get; set; }

    public DateOnly? Birthday { get; set; }

    public bool? IsOmiCall { get; set; }

    public string OmiCallRole { get; set; }

    public string OmiCallPassword { get; set; }

    public int? OmiCallSipUser { get; set; }

    public string OmiCallSecretKey { get; set; }

    public string OmiCallDomain { get; set; }

    public bool? IsKol { get; set; }

    public int? CountOrdersFinish { get; set; }

    public double? TotalOrdersFinish { get; set; }

    public string InvoiceCompanyName { get; set; }

    public string InvoiceEmail { get; set; }

    public string InvoiceTaxCode { get; set; }

    public string InvoiceAddress { get; set; }

    public bool? IsAutoTax { get; set; }

    public string Platform { get; set; }

    public string Version { get; set; }

    public double? TotalSales { get; set; }

    public int? CountSales { get; set; }

    public double? TotalRewards { get; set; }
}