// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Themes
{
    public int Id { get; set; }

    public string Code { get; set; }

    /// <summary>
    /// Tên theme
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ICollection<UserWebs> UserWebs { get; set; } = new List<UserWebs>();
}