// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class UserAddress
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public int? IdProvince { get; set; }

    public int? IdDistrict { get; set; }

    public int? IdWard { get; set; }

    public string Address { get; set; }

    public string FullAddress { get; set; }

    public int? IdType { get; set; }

    public bool? IsDefault { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool? IsSyn { get; set; }

    /// <summary>
    /// Khi thêm cửa hàng update IdShop vào địa chỉ cần thêm
    /// </summary>
    public string AddShops { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public virtual Users User { get; set; }

    public virtual ICollection<UserAddressShopLocations> UserAddressShopLocations { get; set; } = new List<UserAddressShopLocations>();
}