// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class UserAddressShopLocations
{
    public int Id { get; set; }

    public int? IdShop { get; set; }

    public int? IdUserAddress { get; set; }

    public int? UserId { get; set; }

    public double? Distance { get; set; }

    public double? Duration { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public bool? IsActived { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? IndexShop { get; set; }

    public int? IdClient { get; set; }

    public virtual Shops IdShopNavigation { get; set; }

    public virtual UserAddress IdUserAddressNavigation { get; set; }

    public virtual Users User { get; set; }
}