// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class UserWebs
{
    public int Id { get; set; }

    public int UserId { get; set; }

    /// <summary>
    /// Tên miền con theo linkorder
    /// </summary>
    public string SubDomain { get; set; }

    /// <summary>
    /// Tên miền riêng
    /// </summary>
    public string Domain { get; set; }

    /// <summary>
    /// 2: Đã thành công, 1: đang xử lý
    /// </summary>
    public int? DomainStatus { get; set; }

    /// <summary>
    /// Ngày đăng ký
    /// </summary>
    public DateTime? DomainCreatedDate { get; set; }

    /// <summary>
    /// Ngày hết hạn
    /// </summary>
    public DateTime? DomainExpirationDate { get; set; }

    public int? IdTheme { get; set; }

    /// <summary>
    /// Ảnh nền web
    /// </summary>
    public string Background { get; set; }

    /// <summary>
    /// Mô tả linkorder
    /// </summary>
    public string Description { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Themes IdThemeNavigation { get; set; }

    public virtual Users User { get; set; }
}