// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WarehouseHistories
{
    public int Id { get; set; }

    /// <summary>
    /// Mã tham chiếu:1 operations
    /// </summary>
    public int? IdObject { get; set; }

    public int? IdPharmacy { get; set; }

    public int? IdWarehouse { get; set; }

    /// <summary>
    /// Loai hành động nhập, xuất,...
    /// </summary>
    public int? IdWarehouseOperation { get; set; }

    public int? IdProductPharmacy { get; set; }

    public int? IdProduct { get; set; }

    /// <summary>
    /// Id ps
    /// </summary>
    public int? IdProductRef { get; set; }

    public int? Quantity { get; set; }

    public int? IdOrder { get; set; }

    public string OrderCode { get; set; }

    public int? IdOrderOffline { get; set; }

    public string OrderCodeOffline { get; set; }

    public string Descriptions { get; set; }

    /// <summary>
    /// 1: Nhập hàng tự động ;2: Nhập hàng thủ công; 3:chuyển kho ; 4:Xuất hàng thủ công; 5: Xuất hàng bán lẻ; 6: Hủy xuất hàng bán lẻ
    /// </summary>
    public int? TypeObject { get; set; }

    public int? IdProductUnitConvert { get; set; }

    public int? IdProductUnitConvertValue { get; set; }

    public bool? IsAuto { get; set; }

    public bool? IsProcessed { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int? QuantityInventory { get; set; }

    public virtual SaleOrders IdOrderNavigation { get; set; }

    public virtual Products IdProductNavigation { get; set; }

    public virtual Warehouses IdWarehouseNavigation { get; set; }
}