// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WarehouseInOuts
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    /// <summary>
    /// Tiền tố đầu tiên trong mã phiếu
    /// </summary>
    public string PreFix { get; set; }

    public int? IdClient { get; set; }

    public int IdWarehouse { get; set; }

    /// <summary>
    /// Loai hành động nhập, xuất,...
    /// </summary>
    public int IdWarehouseOperation { get; set; }

    /// <summary>
    /// Nhà cung cấp
    /// </summary>
    public int? IdSupplier { get; set; }

    public string Descriptions { get; set; }

    /// <summary>
    /// Trạng thái của phiếu nhập xuất
    /// </summary>
    public int? IdWarehouseInOutStatus { get; set; }

    public bool? IsProcessed { get; set; }

    /// <summary>
    /// ngày dự kiến đối với loại phiếu là kế hoạch
    /// </summary>
    public DateTime? ExpectedDate { get; set; }

    /// <summary>
    /// số tiền mặt thanh toán cho đơn hàng
    /// </summary>
    public double? Cash { get; set; }

    /// <summary>
    /// số tiền thanh toán chuyển khoản
    /// </summary>
    public double? BankTransfer { get; set; }

    /// <summary>
    /// mức chiết khấu cho phiếu
    /// </summary>
    public double? Discount { get; set; }

    /// <summary>
    /// Ngày nhập kho
    /// </summary>
    public DateTime? InputDate { get; set; }

    /// <summary>
    /// ngày thanh toán phiếu
    /// </summary>
    public DateTime? PaymentDate { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Clients IdClientNavigation { get; set; }

    public virtual WarehouseInOutStatus IdWarehouseInOutStatusNavigation { get; set; }

    public virtual Warehouses IdWarehouseNavigation { get; set; }

    public virtual WarehouseOperations IdWarehouseOperationNavigation { get; set; }

    public virtual ICollection<WarehouseInOutDetails> WarehouseInOutDetails { get; set; } = new List<WarehouseInOutDetails>();
}