// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WarehouseInOutDetails
{
    public int Id { get; set; }

    public int IdWarehouseInOut { get; set; }

    public int IdProduct { get; set; }

    public int? Quantity { get; set; }

    /// <summary>
    /// Giá nhập tại thời điểm
    /// </summary>
    public double? Price { get; set; }

    /// <summary>
    /// mô tả khi nhập
    /// </summary>
    public string DescriptionProduct { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Products IdProductNavigation { get; set; }

    public virtual WarehouseInOuts IdWarehouseInOutNavigation { get; set; }
}