// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WarehouseProducts
{
    public int Id { get; set; }

    public int? IdWarehouse { get; set; }

    public int? IdPharmacy { get; set; }

    public int IdProductPharmacy { get; set; }

    public int? IdProduct { get; set; }

    /// <summary>
    /// Số lượng tồn tại trong kho
    /// </summary>
    public int? Quantity { get; set; }

    /// <summary>
    /// Số lượng sản phẩm có thể bán
    /// </summary>
    public int? QuantityCanSell { get; set; }

    /// <summary>
    /// Số lượng số lượng tối thiểu
    /// </summary>
    public int? QuantityMin { get; set; }

    /// <summary>
    /// Số lượng tối đa
    /// </summary>
    public int? QuantityMax { get; set; }

    /// <summary>
    /// Thứ tự
    /// </summary>
    public int? Sort { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Products IdProductNavigation { get; set; }

    public virtual Warehouses IdWarehouseNavigation { get; set; }
}