// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class Warehouses
{
    public int Id { get; set; }

    public int? IdClient { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int? IdProvince { get; set; }

    public int? IdDistrict { get; set; }

    public int? IdWard { get; set; }

    /// <summary>
    /// Địa chỉ kho
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// Người liên hệ khi ship nhận hàng
    /// </summary>
    public string Contact { get; set; }

    /// <summary>
    /// Số điện thoại liên hệ kho
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// Cho phép xuất âm, mặc định false
    /// </summary>
    public bool? IsNegative { get; set; }

    /// <summary>
    /// Phạm vi hoạt động của kho hàng theo tỉnh thành
    /// </summary>
    public string ProvinceActivities { get; set; }

    /// <summary>
    /// Thứ tự
    /// </summary>
    public int? Sort { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual Clients IdClientNavigation { get; set; }

    public virtual ICollection<WarehouseHistories> WarehouseHistories { get; set; } = new List<WarehouseHistories>();

    public virtual ICollection<WarehouseInOuts> WarehouseInOuts { get; set; } = new List<WarehouseInOuts>();

    public virtual ICollection<WarehouseProducts> WarehouseProducts { get; set; } = new List<WarehouseProducts>();
}