// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WarehouseInOutTemps
{
    public int Id { get; set; }

    public int? IdWarehouseInOutOperations { get; set; }

    public int? IdPharmacy { get; set; }

    public int? IdWarehouse { get; set; }

    public int? IdProductPharmacy { get; set; }

    public int? IdProduct { get; set; }

    public int? IdWarehouseOperations { get; set; }

    public int? Quantity { get; set; }

    /// <summary>
    /// 1: Nhập hàng tự động ;2: Nhập hàng thủ công; 3:chuyển kho ; 4:Xuất hàng thủ công; 5: Xuất hàng bán lẻ 
    /// </summary>
    public int? TypeObject { get; set; }

    public bool? IsAuto { get; set; }

    public int? IdProductUnitConvert { get; set; }

    public int? IdProductUnitConvertValue { get; set; }

    public string Descriptions { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }
}