// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WmNotes
{
    public int Id { get; set; }

    public int? IdProject { get; set; }

    public string Name { get; set; }

    public string Detail { get; set; }

    /// <summary>
    /// Màu nền
    /// </summary>
    public string BgColor { get; set; }

    public int? Sort { get; set; }

    public bool? IsStar { get; set; }

    public bool? IsPublic { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }
}