// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

/// <summary>
/// Người tham gia
/// </summary>
public partial class WmParticipants
{
    public int Id { get; set; }

    public int IdTask { get; set; }

    public int UserId { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual WmTasks IdTaskNavigation { get; set; }

    public virtual Users User { get; set; }
}