// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WmProjectMembers
{
    public int Id { get; set; }

    public int IdProject { get; set; }

    public int UserId { get; set; }

    /// <summary>
    /// 1. Quản lý dự án, 2. Giám sát(Xem và sửa công việc), 3. Theo dõi (Chỉ xem và không được sửa)
    /// </summary>
    public int? Role { get; set; }

    public bool? IsProjectManager { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual WmProjects IdProjectNavigation { get; set; }

    public virtual Users User { get; set; }
}