// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WmProjectCols
{
    public int Id { get; set; }

    public int? IdProject { get; set; }

    /// <summary>
    /// Sprint của My task
    /// </summary>
    public int? UserId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    /// <summary>
    /// 1. ToDo, 2. InProgress, 3. Done
    /// </summary>
    public int? IdStatus { get; set; }

    public int? Sort { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual WmProjects IdProjectNavigation { get; set; }

    public virtual ICollection<WmTasks> WmTasks { get; set; } = new List<WmTasks>();
}