// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WmProjects
{
    public int Id { get; set; }

    public int? IdParent { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    public int? Sort { get; set; }

    /// <summary>
    /// Có quy trình không ?
    /// </summary>
    public bool? IsWorkFolow { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual ICollection<WmProjectCols> WmProjectCols { get; set; } = new List<WmProjectCols>();

    public virtual ICollection<WmProjectMembers> WmProjectMembers { get; set; } = new List<WmProjectMembers>();

    public virtual ICollection<WmShortCutLinks> WmShortCutLinks { get; set; } = new List<WmShortCutLinks>();

    public virtual ICollection<WmSprints> WmSprints { get; set; } = new List<WmSprints>();

    public virtual ICollection<WmTasks> WmTasks { get; set; } = new List<WmTasks>();
}