// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WmTaskComments
{
    public int Id { get; set; }

    public int IdTask { get; set; }

    public string Message { get; set; }

    /// <summary>
    /// Ảnh đại diện
    /// </summary>
    public string Image { get; set; }

    public int? Sort { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int? UserId { get; set; }

    public bool? IsActived { get; set; }

    public int? IdParent { get; set; }

    public virtual WmTasks IdTaskNavigation { get; set; }

    public virtual Users User { get; set; }

    public virtual ICollection<WmTaskCommentLikes> WmTaskCommentLikes { get; set; } = new List<WmTaskCommentLikes>();
}