// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WmTasks
{
    public int Id { get; set; }

    public int? IdProject { get; set; }

    public int? IdSprint { get; set; }

    public int? IdProjectCol { get; set; }

    /// <summary>
    /// Nhãn/Trang của task
    /// </summary>
    public int? IdLabel { get; set; }

    /// <summary>
    /// 1. Task, 2. Bug
    /// </summary>
    public int? Type { get; set; }

    /// <summary>
    /// Người chủ trì
    /// </summary>
    public int? IdAssignee { get; set; }

    /// <summary>
    /// Người tam gia
    /// </summary>
    public string Participant { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Detail { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    /// <summary>
    /// 1 Rất cao, 2 Cao, 3 Bình thường , 4 Thấp, 5 Rất thấp
    /// </summary>
    public int? Priority { get; set; }

    /// <summary>
    /// 1. ToDo, 2. InProgress, 3. Done
    /// </summary>
    public int? IdStatus { get; set; }

    /// <summary>
    /// Phần trăm công việc
    /// </summary>
    public int? Percent { get; set; }

    /// <summary>
    /// File đính kèm
    /// </summary>
    public string Attachment { get; set; }

    /// <summary>
    /// Đánh sao
    /// </summary>
    public bool? Star { get; set; }

    public decimal? SortColumn { get; set; }

    public decimal? Sort { get; set; }

    public bool? Completed { get; set; }

    public bool? IsActived { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public virtual Users IdAssigneeNavigation { get; set; }

    public virtual WmLabels IdLabelNavigation { get; set; }

    public virtual WmProjectCols IdProjectColNavigation { get; set; }

    public virtual WmProjects IdProjectNavigation { get; set; }

    public virtual WmSprints IdSprintNavigation { get; set; }

    public virtual ICollection<WmParticipants> WmParticipants { get; set; } = new List<WmParticipants>();

    public virtual ICollection<WmTaskComments> WmTaskComments { get; set; } = new List<WmTaskComments>();

    public virtual ICollection<WmTaskLogs> WmTaskLogs { get; set; } = new List<WmTaskLogs>();
}