// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Work.DataContext.Models;

public partial class WmTaskCommentLikes
{
    public int Id { get; set; }

    public int IdTask { get; set; }

    /// <summary>
    /// Mã sản phẩm
    /// </summary>
    public int IdTaskComment { get; set; }

    /// <summary>
    /// CTV
    /// </summary>
    public int UserId { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CreatedUserId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedUserId { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? DeletedUserId { get; set; }

    public DateTime? DeletedDate { get; set; }

    public virtual WmTaskComments IdTaskCommentNavigation { get; set; }

    public virtual Users User { get; set; }
}